<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Dapper" Version="2.1.66" />
	  <PackageReference Include="MediatR" Version="13.0.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="..\..\Common\Common.ChckHelper\Common.ChckHelper.csproj" />
    <ProjectReference Include="..\Shop.Application\Shop.Application.csproj" />
    <ProjectReference Include="..\Shop.Query\Shop.Query.csproj" />
  </ItemGroup>

</Project>
