<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Users\Addresses\GetByList\" />
    <Folder Include="Users\Addresses\GetById\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="..\..\Common\Common.Query\Common.Query.csproj" />
    <ProjectReference Include="..\Shop.Domain\Shop.Domain.csproj" />
    <ProjectReference Include="..\Shop.Infrastucture\Shop.Infrastucture.csproj" />
  </ItemGroup>

</Project>
